logbookApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
    path("home/", views.home_view, name="home"),
    path("comments/<int:climb_id>/", views.comments_view, name="comments"),
    path("ascent/", views.AscentView.as_view(), name="ascent"),
    path("logbook/", views.logbook_view, name="logbook"),
    path("logbookUpdate/<int:ascent_id>", views.LogbookUpdateView.as_view(), name="logbookUpdate"),
    path("logbookDelete/<int:pk>", views.LogbookDeleteView.as_view(), name="logbookDelete"),
]

my8a/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("logbookApp.urls"))
]

logbookApp/models.py
from django.db import models
from django.contrib.auth.models import User

# represents a boulder problem 
class Climb(models.Model):
    AREAS = [
        ("lcc", "Little Cottonwood Canyon"),
        ("o", "Ogden") 
    ]
    
    name = models.CharField(max_length=100)
    grade = models.CharField(max_length=10)
    area = models.CharField(max_length=3, choices=AREAS, default="lcc")
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.name
    
# represents a log of a climb -> user ascending a climb
class Ascent(models.Model):
    TYPE =[
        ("o", "onsight"),
        ("f", "flash"),
        ("r", "redpoint")
    ]
    
    climb = models.ForeignKey(Climb, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    proposedGrade = models.CharField(max_length=10)
    type = models.CharField(max_length=1 ,choices=TYPE)
    date = models.DateField()
    comment = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.climb} - {self.user}"

logbookApp/forms.py
from django import forms
from .models import Ascent

# form to fill in the fields related to loggin an ascent
class AscentForm(forms.ModelForm):
    # date picker plug in
    date = forms.DateField(
        widget=forms.DateInput(
            attrs={"type": "date"} 
        )
    )
    
    class Meta:
        model = Ascent
        fields = ["proposedGrade", "type", "date", "comment"]

logbookApp/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.db.models import IntegerField
from django.db.models.functions import Cast, Substr
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.generic.edit import DeleteView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

from .models import Climb, Ascent
from .forms import AscentForm
import re

def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")  # make sure you have a 'login' URL name
    else:
        form = UserCreationForm()
    
    return render(request, "logbookApp/register.html", {"form": form})

# classic log in view 
def login_view(request):
    form = AuthenticationForm(request, data=request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("home")

    return render(request, "logbookApp/login.html", {"form": form})

# shows all available climbs to log
def home_view(request):
    climbs_lcc = Climb.objects.filter(area="lcc").annotate(grade_num=Cast(Substr("grade", 2), IntegerField())).order_by("grade_num")
    climbs_o = Climb.objects.filter(area="o").annotate(grade_num=Cast(Substr("grade", 2), IntegerField())).order_by("grade_num")
    context = {"climbs_lcc": climbs_lcc, "climbs_o": climbs_o, "user": request.user}
    return render(request, "logbookApp/home.html", context)

# form view to log an ascent of a climb - takes climb name from request to display
class AscentView(FormView):
    template_name = "logbookApp/ascent.html"
    form_class = AscentForm
    success_url = "/logbook/"
    
    # used to pre populate the update form with current ascent data
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        ascent_id = self.kwargs.get("ascent_id")
        if ascent_id:
            ascent = get_object_or_404(Ascent, id=self.kwargs["ascent_id"], user=self.request.user)
            kwargs["instance"] = ascent
        return kwargs

    def form_valid(self, form):
        ascent = form.save(commit=False)
        ascent.user = self.request.user
        
        # make sure the grade input is proceeded by v
        proposedGrade = form.cleaned_data.get("proposedGrade")
        result = re.match(r'^[Vv]\d+$', proposedGrade)
        if not result:
            form.add_error("proposedGrade", "grade must start with v")
            return self.form_invalid(form)
        
        # grab the passed in climb
        climb_id = self.request.GET.get("climb_id")
        if climb_id:
            ascent.climb = get_object_or_404(Climb, id=climb_id)
        
        ascent.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # get ascent info if availaible
        ascent_id = self.kwargs.get("ascent_id")
        if ascent_id:
            ascent = get_object_or_404(Ascent, id=self.kwargs["ascent_id"], user=self.request.user)
            context["ascent"] = ascent
        
        # get climb info if available
        climb_id = self.request.GET.get("climb_id")
        if climb_id:
            context["climb"] = get_object_or_404(Climb, id=climb_id)
        return context
            
# pass all the ascents of the loggin in user 
def logbook_view(request):
    loggedAscents = Ascent.objects.filter(user=request.user).order_by('-date')
    context = {"loggedAscents": loggedAscents}
    return render(request, "logbookApp/logbook.html", context)

# filter climb and climb comments from the passed in id via url
def comments_view(request, climb_id):
    climb = Climb.objects.get(id=climb_id)
    comments = Ascent.objects.filter(climb_id=climb_id).exclude(comment="")
    context = {"climb": climb, "comments": comments}
    
    return render(request, "logbookApp/comments.html", context)
    

# update existing Ascent view class
class LogbookUpdateView(AscentView):
    model = Ascent
    template_name = "logbookApp/logbookUpdate.html"
    form_class = AscentForm
    success_url = "/logbook/"

# delete existing pi view class
class LogbookDeleteView(DeleteView):
     model = Ascent
     template_name = "logbookApp/logbookDelete.html"
     success_url = "/logbook/"

     def get_queryset(self):
        return Ascent.objects.filter(user=self.request.user)

logbookApp/templates/logbookApp/ascent.html
{% extends "logbookApp/base.html" %} {% block content %}

<div class="main-container">
  <h2>Log Ascent for: {{climb.name}} ({{climb.grade}})</h2>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Log</button>
  </form>
  <br />
  <a href="{% url 'home' %}">Home</a>
</div>

{% endblock %}

logbookApp/templates/logbookApp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Climb Logbook{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'logbookApp/css/style.css' %}" />
  </head>
  <body>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

logbookApp/templates/logbookApp/comments.html
{% extends "logbookApp/base.html" %} {% block content %}

<div class="main-container">
  <h1>Comments for: {{climb.name}}</h1>

  <ul>
    {% if comments|length == 0 %}
    <p>No comments to show...</p>
    {% else %} {% for comment in comments %}
    <li>
      <strong>{{comment.user.username}}</strong> said: {{comment.comment}}
    </li>
    <pre><strong>Proposed grade on {{comment.date}} of: </strong>{{comment.proposedGrade}} [{{comment.get_type_display}}]</pre>
    {% endfor %} {%endif%}
  </ul>
  <a href="{% url 'home' %}">Home</a>
</div>

{% endblock %}

logbookApp/templates/logbookApp/home.html
{% extends "logbookApp/base.html" %} {% block content %}

<div class="main-container">
  <h1>8a.nu Lite</h1>
  <h2>Welcome {{user.username}}</h2>
  <p>Search the database and log you sends!</p>
  <a href="{% url 'logbook' %}">See logbook</a>

  <div id="lcc-container">
    <h2>Little Cottonwood Canyon</h2>
    <table>
      <tr>
        <th>Climb</th>
        <th>Grade</th>
        <th>Description</th>
        <th>View Comments</th>
        <th>Log Option</th>
      </tr>
      {% for climb in climbs_lcc %}
      <tr>
        <td>{{climb.name}}</td>
        <td>{{climb.grade}}</td>
        <td>{{climb.description}}</td>
        <td>
          <a href="{% url 'comments' climb.id %}">View Comments</a>
        </td>
        <td>
          <a href="{% url 'ascent' %}?climb_id={{ climb.id }}">Log Ascent</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>

  <div id="ogden-container">
    <h2>Ogden</h2>
    <table>
      <tr>
        <th>Climb</th>
        <th>Grade</th>
        <th>Description</th>
        <th>View Comments</th>
        <th>Log Option</th>
      </tr>
      {% for climb in climbs_o %}
      <tr>
        <td>{{climb.name}}</td>
        <td>{{climb.grade}}</td>
        <td>{{climb.description}}</td>
        <td>
          <a href="{% url 'comments' climb.id %}">View Comments</a>
        </td>
        <td>
          <a href="{% url 'ascent' %}?climb_id={{ climb.id }}">Log Ascent</a>
        </td>
      </tr>
      {% endfor %}
    </table>
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>
  </div>
</div>

{% endblock %}

logbookApp/templates/logbookApp/logbook.html
{% extends "logbookApp/base.html" %} {% block content %}

<div class="main-container">
  <h1>Logbook</h1>

  {% if loggedAscents|length == 0 %}
  <p>No logged climbs to see... go outside ASAP!</p>
  <ul>
    {% else %}{% for ascent in loggedAscents %}
    <li>
      {{ascent.climb}} ({{ascent.proposedGrade}}) in
      {{ascent.climb.get_area_display}}
      <br />
      <pre>
<strong>{{ascent.get_type_display}} on {{ascent.date}}:</strong> {{ascent.comment}}</pre>
    </li>
    <a href="{% url 'logbookUpdate' ascent.id %}">|Update Ascent|</a>
    <a href="{% url 'logbookDelete' ascent.id %}">|Delete Ascent|</a>
    {% endfor %}{% endif %}
  </ul>
  <br />
  <a href="{% url 'home' %}">Home</a>
</div>

{% endblock %}

logbookApp/templates/logbookApp/logbookDelete.html
{% extends "logbookApp/base.html" %} {% block content %}

<div class="main-container">
  <h3>Are you sure you want to delete this ascent: {{ascent.climb.name}}?</h3>

  <form method="post">
    {% csrf_token %} <input type="submit" value="Delete" />
  </form>
  <br />
  <a href="{% url 'logbook' %}">Cancel</a>

  {%endblock%}
</div>

logbookApp/templates/logbookApp/logbookUpdate.html
{% extends "logbookApp/base.html" %} {% block content %}

<div class="main-container">
  <h1>Update Logbook Entry for: {{ascent.climb.name}}</h1>

  <form method="post">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Submit Update" />
  </form>
  <br />
  <a href="{% url 'logbook' %}">Cancel</a>
</div>
{%endblock%}

logbookApp/templates/logbookApp/login.html
{% extends "logbookApp/base.html" %} {% block content %}
<div class="main-container">
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Login</button>
  </form>

  <br />
  <a href="{% url 'register' %}">Just kidding?</a>
</div>
{%endblock%}

logbookApp/templates/logbookApp/register.html
{% extends "logbookApp/base.html" %} {% block content %}
<div class="main-container">
  <h1>Create an Account</h1>

  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>

  <p>Already have an account? <a href="{% url 'login' %}">Log in here</a></p>
</div>
{%endblock%}